# Generated by Django 4.2.7 on 2023-12-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=255, verbose_name='Марка, модель')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('gos_number', models.CharField(max_length=10, verbose_name='Гос.№')),
                ('norma', models.FloatField()),
                ('mileage', models.FloatField()),
                ('operating_time', models.FloatField(blank=True)),
                ('driver', models.CharField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('post', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=True, verbose_name='Исправна')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Парк техники',
                'verbose_name_plural': 'Парк техники',
                'ordering': ['-time_create', 'marka'],
            },
        ),
    ]
